### ISSUE TITLE
Mod seems to break with ChoiceTheorem's Overhauled Villages [Fabric 1.20.2] [Sparse Structures 2.0/CTOV 3.3.5b]

### ISSUE THREAD

**Issue by JuceDoesThings** [MaxenceDC/sparsestructures#5]
Upon attempting to start a server with just the mod Sparse Structures and ChoiceTheorem's Overhauled Villages, I get this strange error in my log

```[21:34:19] [main/INFO]: Loading Minecraft 1.20.2 with Fabric Loader 0.14.24
[21:34:19] [ForkJoinPool-1-worker-2/WARN]: Mod ctov uses the version 3.3.5b which isn't compatible with Loader's extended semantic version format (Could not parse version number component '5b'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[21:34:19] [main/INFO]: Loading 42 mods:
	- ctov 3.3.5b
	- fabric-api 0.90.7+1.20.2
	   |-- fabric-api-base 0.4.33+fce67b32a0
	   |-- fabric-api-lookup-api-v1 1.6.42+b1792f7da0
	   |-- fabric-biome-api-v1 13.0.14+b1792f7da0
	   |-- fabric-block-api-v1 1.0.12+73761d2ea0
	   |-- fabric-block-view-api-v2 1.0.1+73761d2ea0
	   |-- fabric-blockrenderlayer-v1 1.1.43+f4b7e424a0
	   |-- fabric-client-tags-api-v1 1.1.4+86b12645a0
	   |-- fabric-command-api-v1 1.2.37+f71b366fa0
	   |-- fabric-command-api-v2 2.2.16+b1792f7da0
	   |-- fabric-commands-v0 0.2.54+df3654b3a0
	   |-- fabric-containers-v0 0.1.75+df3654b3a0
	   |-- fabric-content-registries-v0 5.0.5+b1792f7da0
	   |-- fabric-convention-tags-v1 1.5.8+b1792f7da0
	   |-- fabric-crash-report-info-v1 0.2.20+f4b7e424a0
	   |-- fabric-data-generation-api-v1 13.1.5+b1792f7da0
	   |-- fabric-dimensions-v1 2.1.57+b1792f7da0
	   |-- fabric-entity-events-v1 1.5.26+b1792f7da0
	   |-- fabric-events-interaction-v0 0.6.10+b1792f7da0
	   |-- fabric-events-lifecycle-v0 0.2.69+df3654b3a0
	   |-- fabric-game-rule-api-v1 1.0.42+a44e16a6a0
	   |-- fabric-item-api-v1 2.1.33+b1792f7da0
	   |-- fabric-item-group-api-v1 4.0.15+e3d2bf3fa0
	   |-- fabric-key-binding-api-v1 1.0.38+f4b7e424a0
	   |-- fabric-keybindings-v0 0.2.36+df3654b3a0
	   |-- fabric-lifecycle-events-v1 2.2.27+b1792f7da0
	   |-- fabric-loot-api-v2 2.1.1+3ba460fba0
	   |-- fabric-message-api-v1 6.0.2+e3d2bf3fa0
	   |-- fabric-mining-level-api-v1 2.1.55+f4b7e424a0
	   |-- fabric-model-loading-api-v1 1.0.6+b1792f7da0
	   |-- fabric-models-v0 0.4.5+9386d8a7a0
	   |-- fabric-networking-api-v1 3.0.11+bff13c85a0
	   |-- fabric-object-builder-api-v1 12.1.2+2ff98d3ba0
	   |-- fabric-particles-v1 1.1.4+f4b7e424a0
	   |-- fabric-recipe-api-v1 2.0.8+52b3ebe5a0
	   |-- fabric-registry-sync-v0 4.0.6+b1792f7da0
	   |-- fabric-renderer-api-v1 3.2.1+2034447ca0
	   |-- fabric-renderer-indigo 1.5.1+2034447ca0
	   |-- fabric-renderer-registries-v1 3.2.49+df3654b3a0
	   |-- fabric-rendering-data-attachment-v1 0.3.39+73761d2ea0
	   |-- fabric-rendering-fluids-v1 3.0.30+f4b7e424a0
	   |-- fabric-rendering-v0 1.1.52+df3654b3a0
	   |-- fabric-rendering-v1 3.0.11+b1792f7da0
	   |-- fabric-resource-conditions-api-v1 2.3.10+e3d2bf3fa0
	   |-- fabric-resource-loader-v0 0.11.12+b1792f7da0
	   |-- fabric-screen-api-v1 2.0.12+b1792f7da0
	   |-- fabric-screen-handler-api-v1 1.3.41+b1792f7da0
	   |-- fabric-sound-api-v1 1.0.14+f4b7e424a0
	   |-- fabric-transfer-api-v1 3.3.10+bb1ee60ea0
	   \-- fabric-transitive-access-wideners-v1 5.0.3+fce67b32a0
	- fabricloader 0.14.24
	- java 21
	- minecraft 1.20.2
	- sparsestructures 2.0
[21:34:19] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Sefu%20Gaming/Desktop/JamsSMP/1.20.2/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[21:34:20] [main/INFO]: Compatibility level set to JAVA_16
[21:34:20] [main/INFO]: Compatibility level set to JAVA_17
[21:34:27] [main/INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[21:34:29] [main/ERROR]: Registry loading errors:
> Errors in registry minecraft:worldgen/structure_set:
>> Errors in element minecraft:pillager_outpost:
java.lang.IllegalStateException: Failed to parse minecraft:worldgen/structure_set/pillager_outpost.json from pack fabric
	at net.minecraft.class_7655.method_45122(class_7655.java:179)
	at net.minecraft.class_7655$class_7657.method_45132(class_7655.java:61)
	at net.minecraft.class_7655.method_45120(class_7655.java:98)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.class_7655.method_45121(class_7655.java:98)
	at net.minecraft.class_7237.method_45142(class_7237.java:67)
	at net.minecraft.class_7237.method_45143(class_7237.java:71)
	at net.minecraft.class_7237.method_42098(class_7237.java:34)
	at net.minecraft.server.Main.method_43612(Main.java:159)
	at net.minecraft.class_156.method_43498(class_156.java:945)
	at net.minecraft.class_156.method_43499(class_156.java:939)
	at net.minecraft.server.Main.main(Main.java:157)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
Caused by: java.lang.RuntimeException: Value 6400 outside of range [0:4096]
	at com.mojang.serialization.DataResult.lambda$getOrThrow$5(DataResult.java:101)
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99)
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93)
	at net.minecraft.class_7655.method_45122(class_7655.java:176)
	... 15 more

[21:34:29] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Failed to load registries due to above errors
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:206) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
Caused by: java.lang.IllegalStateException: Failed to load registries due to above errors
	at net.minecraft.class_7655.method_45121(class_7655.java:111) ~[server-intermediary.jar:?]
	at net.minecraft.class_7237.method_45142(class_7237.java:67) ~[server-intermediary.jar:?]
	at net.minecraft.class_7237.method_45143(class_7237.java:71) ~[server-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:34) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.method_43612(Main.java:159) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:945) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:939) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:157) ~[server-intermediary.jar:?]
	... 4 more
```

I'm not quite sure what could be causing this! As you can see, though, the error happens when only using the three mods. As it shows something to do with datapacks not loading properly, which makes me think that perhaps Sparse Structures interferes poorly with datapacks as a whole and CTOV happens to behave like a datapack? Not sure

**Comment by MaxenceDC** [comment]
Hmm that's interesting, I'll see if I can reproduce it this weekend, thanks for the report.  In the meantime you can use v1.0, this version shouldn't cause any issue. I personally use CTOV with v2, but I don't get this crash, that's strange.

**Comment by MaxenceDC** [comment]
I've narrowed down the issue, and it's caused by #8. Will be fixed in 2.1.
